### ISSUE TITLE
Darken selected item background

### ISSUE THREAD

**Issue by LeviSnoot** [WDaan/VueTorrent#1208]
Should be a pretty simple fix but I'm not read up enough on Vue to tackle it myself yet.

Right now the background for selected items (`.v-application .torrent-{status}`) is way too bright to view comfortably.

This can be solved by changing the var for `.v-application .torrent-{status}` from (using `.v-application .torrent-uploading` as an example)

```css
.v-application .torrent-uploading {
	background-color: var(--v-torrent-uploading-base) !important;
	border-color: var(--v-torrent-uploading-base) !important;
}
```

![image](https://github.com/WDaan/VueTorrent/assets/13402525/ea3138d0-16c3-4ac1-96f8-a19e953866b5)

to

```css
.v-application .torrent-uploading {
	background-color: var(--v-torrent-uploading-darken3) !important;
	border-color: var(--v-torrent-uploading-base) !important;
}
```

![image](https://github.com/WDaan/VueTorrent/assets/13402525/209f9525-e3eb-4419-95dc-3e49ead1647c)

The progress bars should be set to their own class after this and use `var(--v-torrent-{status}-base)` for good measure.
