### ISSUE TITLE
Icons in the navbar are not centered

### ISSUE THREAD

**Issue by kazik56** [WDaan/VueTorrent#14]
As in the title. To fix remove following CSS:
```css
.v-application .pr-2 {
    padding-right: 8px !important;
}
```
Before:
![image](https://user-images.githubusercontent.com/24499074/83285936-a6ae5800-a1ce-11ea-8330-d353813af707.png)
After:
![image](https://user-images.githubusercontent.com/24499074/83285905-9ac29600-a1ce-11ea-9c7f-d3a522c4f808.png)

**Comment by kazik56** [comment]
After removing the padding you will notice that there is now some space unused. This can be further improved by modifying following CSS:
```css
.justify-space-between {
    position: fixed;
    bottom: 0px;
    width: 100%;
}
```
All you have to do then is to `right: 15px;`. This is the only `.justify-space-between` on the page I found so it should be relatively safe to apply style to this class. Hovewer, you might want to keep the inline styling.
