### ISSUE TITLE
[Feature Request] Minimal/Overall view

### ISSUE THREAD

**Issue by hot22shot** [WDaan/VueTorrent#157]
Hi,

Sometimes I have a lot of torrent at the same time. I'd like to have the possibility to have an overall view of all my torrents on the main page maybe with less metrics displayed.

Cheers !

**Comment by WDaan** [comment]
Hi!

Does the data table version fit your needs?  as mentioned in #143 
You can check it out [here](https://github.com/Ov3r1d3/VueTorrent)
It is a fork by @Ov3r1d3 & he would make a pull request once he's finished, but it's taking a little longer than expected (no blame by any means)

**Comment by Ov3r1d3** [comment]
Actually , since I thought I would use it only for me . I kinda threw the
code so it was not good for a merge. I wanted to get on it last weekend
,but I had some issues . But I will probably work on it this week :) .

Sorry for any inconvenience.

**Comment by WDaan** [comment]
No worries at all! 
Even if you did find the time, I'm not sure I would have found the time to look at it.
I'm very excited that you're willing to implement such a great feature.
Don't feel obligated by any means, I'd do it myself when I find the time.

**Comment by hot22shot** [comment]
The data table by @Ov3r1d3 would definitely fit my needs !

**Comment by brandonvu99** [comment]
Any updates on this? Would love it if this were an option that can be toggled!

**Comment by hot22shot** [comment]
To be honest I moved on to flood which gave me that high level view that I needed.

**Comment by WDaan** [comment]
Sure, whatever works for you 🙂 

Haven't gotten around to it yet.
Also thinking/experimenting about a complete rewrite in Vue3.


Lot's of ideas, little time

**Comment by akballow** [comment]
I did not like how flood requires other software to get it working. Sure it does what I want, per this thread but I am giving a +1 for the feature as Vue does what flood does without so many dependencies.

**Comment by firasdib** [comment]
Is there any progress on this? The screenshots look perfect, I'd move over to VueTorrent if it looked like that.

**Comment by WDaan** [comment]
@firasdib the screenshots in this repos readme are fairly accurate. 

Yet there is still no minimal version available as of yet. Could perhaps be part of the vue3 rewrite

**Comment by FluffyDiscord** [comment]
Compact mode would be nice, I would really love to see more than 5 torrents on my screen, something like this would be nice to have officially (excuse the black box):
![Screenshot_1](https://github.com/WDaan/VueTorrent/assets/10332247/5a4cd1fe-e2bd-4f1a-b59b-975c18dbac48)

The css overwrite that screenshot uses.
```css
.v-list-item__content .done > .layout > div > div,
.v-list-item__content .stalled > .layout > div > div,
.v-list-item__content .seeding > .layout > div > div {
    display: flex;
    flex-direction: row;
    gap: 0.5rem;
    flex-basis: auto;
    white-space: nowrap;
    max-width: unset;
    align-items: center;
    font-size: 85%;
}
.v-list-item__content .done > .layout > div,
.v-list-item__content .stalled > .layout > div,
.v-list-item__content .seeding > .layout > div {
    display: grid;
    grid-template-columns: 1fr 100px 150px 170px 100px 80px 190px;
    gap: 2rem;
    padding-block: 3px !important;
}
.v-list-item__content .done > .layout > div > div:first-child,
.v-list-item__content .stalled > .layout > div > div:first-child,
.v-list-item__content .seeding > .layout > div > div:first-child {
    margin-right: auto;
    font-size: 90%;
}

.v-list-item__content .done > .layout > div > div > div:first-child,
.v-list-item__content .stalled > .layout > div > div > div:first-child,
.v-list-item__content .seeding > .layout > div > div > div:first-child {
    font-size: 80% !important;
}
.v-list-item__content .done > .layout > div > div > div:last-child,
.v-list-item__content .stalled > .layout > div > div > div:last-child,
.v-list-item__content .seeding > .layout > div > div > div:last-child {
    margin-left: auto;
}

.pa-0.v-list-item.theme--dark.mb-2 {
    margin-bottom: 0 !important;
}

.v-list-item {
min-height: 30px;
}

.v-list-item__action {
	margin-block: 0px;
}

.v-list-item__action .v-input--selection-controls__ripple {
	left: 0;
    top: 0;
    width: 24px;
    height: 24px;
    margin: 0;
}
```
