### ISSUE TITLE
[Regression] Tab title aren't uppercased

### ISSUE THREAD

**Issue by Larsluph** [WDaan/VueTorrent#965]
#954 introduced a regression on Tab names.

Before: the `text-transform` rule on tabs was written using this syntax.
```css
.v-tab {
  ...
  text-transform: uppercase;
  ...
}
```
![image](https://github.com/WDaan/VueTorrent/assets/22910497/e5693d00-655d-452c-9774-1ebc6d26a470)

After: the `text-transform` rule on tabs is written using double-quotes which invalidates the `uppercase` value
```css
```css
.v-tab {
  ...
  text-transform: "uppercase";
  ...
}
```
![image](https://github.com/WDaan/VueTorrent/assets/22910497/e8d1bc29-f5f2-44dc-b998-1d726db7ce45)
Hint is "Invalid property value" on the ⚠️ icon.

Note: this style rule is added by Vuetify, not VueTorrent.
